name: Duels
version: 1.9.3-SNAPSHOT
main: me.raikou.duels.DuelsPlugin
api-version: 1.21
authors: [Raikou]
description: Professional Duels Core Plugin
commands:
  duel:
    description: Main command for Duels
    usage: /duel <subcommand>
    aliases: [duels]
  lobby:
    description: Teleport to lobby
    usage: /lobby
    aliases: [hub, l]
  stats:
    description: View player statistics
    usage: /stats [player]
permissions:
  duels.admin:
    description: Admin permission for Duels
    default: op
