name: Duels
version: 2.0.0
main: me.raikou.duels.DuelsPlugin
api-version: 1.21
authors: [Raikou]
description: Professional Duels Core Plugin
softdepend: [PlaceholderAPI, LuckPerms]
commands:
  duel:
    description: Main command for Duels
    usage: /duel <subcommand>
    aliases: [duels]
  lobby:
    description: Teleport to lobby
    usage: /lobby
    aliases: [hub, l]
  stats:
    description: View player statistics
    usage: /stats [player]
  ping:
    description: View your connection info
    usage: /ping
  leaderboard:
    description: View the leaderboard
    usage: /leaderboard
    aliases: [lb, top]
  profile:
    description: View player profile
    usage: /profile <player>
  punish:
    description: Punish a player
    usage: /punish <player>
    permission: duels.punish
permissions:
  duels.admin:
    description: Full admin access to all commands
    default: op
  duels.chat.color:
    description: Use MiniMessage colors in chat
    default: op
  duels.chat.bypass:
    description: Bypass chat cooldown and anti-spam
    default: op
